stages:
  - build
  - deploy

before_script:
  - pwd
  - echo $CI_PROJECT_PATH

variables:
  GIT_STRATEGY: clone 

backend1_build:
  stage: build
  script:
    - docker build backend1 $CI_PROJECT_PATH/backend1/additional/

backend2_build:
  stage: build
  script:
    - docker build backend2 $CI_PROJECT_PATH/backend2/multiplication/

frontend_build:
  stage: build
  script:
    - docker build frontend $CI_PROJECT_PATH/frontend/front/