version: '3'
services:
  backend1:
    build: .
    container_name: backend1
    privileged: true
    ports:
      - "8001:8000"
      - "8021:22"
      - "81:80"
    networks:
      - calculator-bridge-network
    command: sleep infinity
  backend2:
    build: .
    privileged: true
    container_name: backend2
    ports:
      - "8002:8000"
      - "8022:22"
      - "82:80"
    networks:
      - calculator-bridge-network
    command: sleep infinity
  frontend:
    build: .
    privileged: true
    container_name: frontend
    ports:
      - "8004:8000"
      - "8003:8003"
      - "8023:22"
      - "83:80"
    networks:
      - calculator-bridge-network
    command: sleep infinity
networks:
  calculator-bridge-network:
    driver: bridge
